# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f843a71b5468977fef02c475e23640a49c14e8e39343c3a2d7c3191bcb57b6324d34f57b4149e3cdbbded7f28d8765e535e0246a71f047178f667ce83736474

test:
  secret_key_base: ecb5d3768eb1b823e49a0abff17855258e3400db72915c2938f24ed25b10a78cfee308efdec89aa51d62ab279907867653847adf892d68be2fc901ba85e4d093

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
